name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: component
    attributes:
      label: Component
      description: Which component has the issue? (Pi, Pico, or Pico W)
      placeholder: "e.g., Pico"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: hardware-setup
    attributes:
      label: Hardware Setup
      description: Describe your hardware configuration
      placeholder: "e.g., Raspberry Pi 3B+, DHT11 on GPIO1, etc."
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output.
      render: shell
